version: "3.8"
services:
  act-app:
    build:
      context: .
    ports:
      - "188.245.69.219:8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@analytical_tools-db-postgres-1:5432/postgres
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db-postgres

  db-postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: