version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres_admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: flask_app
    restart: always
    depends_on:
      - postgres
    environment:
      # This connection string allows the Flask app to reach Postgres by its service name.
      DATABASE_URL: postgres://postgres_admin:${DB_PASSWORD}@postgres:5432/mydb
    ports:
      - "8080:8080"

  apache:
    build: ./frontend
    container_name: apache_frontend
    restart: always
    ports:
      - "80:80"

volumes:
  postgres_data:
