services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  backend:
    build: ./backend
    container_name: flask_app
    restart: always
    depends_on:
      - postgres
    environment:
      # This connection string allows the Flask app to reach Postgres by its service name.
      DATABASE_URL: postgres://postgres:${DB_PASSWORD}@postgres_db:5432/postgres
    ports:
      - "8080:8080"

  apache:
    build: ./frontend
    container_name: apache_frontend
    restart: always
    ports:
      - "8081:80"
    volumes:
      # Mount the live certs from the host
      - /etc/letsencrypt/live/analytical.dispelk9.de/fullchain.pem:/usr/local/apache2/conf/fullchain.pem:ro
      - /etc/letsencrypt/live/analytical.dispelk9.de/privkey.pem:/usr/local/apache2/conf/privkey.pem:ro

volumes:
  postgres_data:
