name: Deploy to server or Storage Box
on: push
jobs:
  Test:
    name: Prepare Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Website Online
        run: |
          server = $(analytical.dispelk9.de)
          if nc -z $server 22 2>/dev/null; then
              echo "$server ✓"
          else
              echo "$server ✗"
          fi

  Deploy:
    runs-on: ubuntu-latest
    needs: Test
    name: Deploy Hetzner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 22 -t ed25519 ${{ secrets.IP}} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          rsync -azP -e "ssh -i $HOME/.ssh/id_ed25519 -p 22" ./ ${{ secrets.ARTIFACT_USERNAME }}@${{ secrets.IP }}:~/analytic_flask/Analytical_tools/