name: Flask Deploy

on:
  push:
    branches:
      - master

jobs:
  updating-infrastructure:
      name: Updating Infrastructure
      runs-on: ubuntu-latest
      env:
          TF_LOG: DEBUG
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install dependencies 
          run: npm i
        - name: Build for production
          run: npm run build

        - name: Setup SSH
          run: |
            mkdir -p ~/.ssh/
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_terra
            echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/github_terra.pub
            chmod 600 ~/.ssh/github_terra
            chmod 600 ~/.ssh/github_terra.pub
            ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
        
        - name: Git clone the Analytical Repos
          run: |
              echo "Prepare to clone the repo"
              git@github.com:Dispelk9/Analytical_tools.git
              echo "Installing the needed packages for Flask"
              apt install python3.10-venv
              apt install pip
          working-directory: /root/

        - name: Run the playbook to activate the website
          uses: ./.github/actions/ansible
          with: 
            playbook: main.yml
            inventory: localhost
          
      