name: Deploy to server or Storage Box
on: push
jobs:
  Test:
    name: Prepare Deploy
    env:
      ACTIONS_STEP_DEBUG: true
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - name: Test Website Online
        run: |
          server=analytical.dispelk9.de
          if nc -z $server 22 2>/dev/null; then
              echo "$server ✓"
          else
              echo "$server ✗"
          fi

  Deploy:
    runs-on: ubuntu-latest
    needs: Test
    if: github.ref == 'refs/heads/master'
    name: Deploy On Hetzner
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up SSH agent with the private key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Docker Compose with ACT
        env:
          DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.IP }} << 'EOF'

            # Export the environment variable for the session
            export DB_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}"
            
            # Update the server and install git if necessary
            sudo apt-get update -y && sudo apt-get install -y git
            
            # Remove old repository
            sudo rm -rf /root/Analytical_tools

            #kill gunicorn server
            #pkill gunicorn
            # sudo rm -rf /root/analytic_flask/Analytical_tools
            
            # Start the SSH agent and add the key with the passphrase
            # cd /root/analytic_flask/

            sudo bash -c 'eval "$(ssh-agent -s)" && echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add /root/.ssh/id_rsa'
            git clone git@github.com:Dispelk9/Analytical_tools.git
            
            #cd /root/analytic_flask/Analytical_tools
            #gunicorn --config gunicorn_config.py adduct_flask:app --certfile=/etc/letsencrypt/live/analytical.dispelk9.de/fullchain.pem --keyfile=/etc/letsencrypt/live/analytical.dispelk9.de/privkey.pem > /tmp/flask_log.txt 2>&1 &
            
            cd Analytical_tools
            docker compose down --volumes
            docker compose build
            docker compose up -d
          
