name: Deploy to server or Storage Box
on: push
jobs:
  Test:
    name: Prepare Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Website Online
        run: |
          server=analytical.dispelk9.de
          if nc -z $server 22 2>/dev/null; then
              echo "$server ✓"
          else
              echo "$server ✗"
          fi

  Deploy:
    runs-on: ubuntu-latest
    needs: Test
    name: Deploy Hetzner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up SSH agent with the private key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Initial Update on Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.IP }} << EOF
            # Update the server and install git if necessary
            sudo apt-get update -y && sudo apt-get install -y git

      - name: Remove the old Repository
        run: |
          sudo rm -rf /root/analytic_flask/Analytical_tools
          # Start the SSH agent and add the key with the passphrase
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add /root/.ssh/id_rsa
          cd /root/analytic_flask/Analytical_tools
          sudo git clone git@github.com:Dispelk9/Analytical_tools.git

      - name: Rerun Gunicorn Server
        run: |
          cd /root/analytic_flask/Analytical_tools
          gunicorn --config gunicorn_config.py adduct_flask:app --certfile=/etc/letsencrypt/live/analytical.dispelk9.de/fullchain.pem --keyfile=/etc/letsencrypt/live/analytical.dispelk9.de/privkey.pem > /tmp/flask_log.txt 2>&1 &

          
